# Define your desired rpc configurations, identified by "key" which must be unique.
# Use the key in other configurations that require rpc servers.

[[rpc]]
key="helius_geyser_free"
url="..."
http_timeout_ms=5000
requests_per_second=10
thread_pool_size=1

[[rpc]]
key="shyft_free"
url="..."
http_timeout_ms=5000
requests_per_second=30
thread_pool_size=1

[[rpc]]
key="quasar_lups"
url="..."
http_timeout_ms=5000
requests_per_second=100
thread_pool_size=1

[jupiter]
url="http://0.0.0.0:8080/"
http_timeout_ms=3000
requests_per_second=0
thread_pool_size=0
unmetered=true

# Miscellaneous bot configuration

[bot_misc]
keypair_path="my-keypair.json" # required for signing transactions
task_scheduler_threads=5 # the amount of threads to execute repeating tasks such as fetching latest blockhashes
token_subscribe_wss_url="..." # used to subscribe to token programs for quoting
address_table_lookup_rpc_keys=["quasar_lups"] # lookup requests will randomly select one of the rpcs to use
address_table_lookup_max_cache_size=1000 # max number of lookup tables to cache
address_table_lookup_timeout_ms=10000 # how long should a lookup request wait before cancelling
latest_blockhash_rpc_keys=["helius_geyser_free"] # each key will schedule a latest blockhash fetch task to ensure the bot has the latest blockhash for transactions
latest_blockhash_fetch_ms=200 # the rate at which latest blockhash fetch tasks should execute
latest_blockhash_timeout_ms=3000 # how long should a fetch task wait before cancelling

# Example strategy settings - do not edit this
[strategy_example_doc]
# Flag used to disable strategies
disabled=false # defaults to false if not set

# Wrap and unwrap Sol - Only applicable if base is SOL (refer to https://station.jup.ag/api-v6/post-swap for info)
wrap_unwrap_sol=true # default value

# Spend limits - Must be set
min_spend=123
max_spend=456

# Priority fee - Define your desired priority fee settings.
# Ex: priorityFeeLamports = (estimatedProfitLamports * priority_fee_profit_factor).max(min_priority_fee_lamports).min(max_priority_fee_lamports)
# If priority_fee_profit_factor is set to 0, the priority fee of the tx will be rand(min_priority_fee_lamports, max_priority_fee_lamports)
priority_fee_profit_factor=0.05 # default value
min_priority_fee_lamports=100 # default value
max_priority_fee_lamports=1000 # default value

# Max compute unit limit - The maximum compute unit limit allowed for a transaction to be sent.
# Transactions with a calculated compute unit limit greater than max_compute_limit will not be sent.
# Warning: Enabling this will cause transactions to simulate first, which is overall slower and uses one more rpc call.
# Disable this setting by simply not including it or setting it to -1
max_compute_limit=-1 # default value

# Max swap routes - The maximum amount of swap routes allowed for a transaction to be sent.
# Disable this setting by simply not including it, although, we recommend this set to 5.
max_swap_routes=5 # default value

# Min profit lamports - The minimum amount of lamports you're willing to accept from a transaction.
# Warning: Setting this too high will cause transaction sto be cancelled on chain, still charging you a network and priority fee.
min_profit_lamports=1 # default value

# Entry quote settings - Refer to https://station.jup.ag/api-v6/get-quote
entry_only_direct_routes=false # default value
entry_restrict_intermediate_tokens=false # default value
entry_min_slippage_bps=2500 # default value
entry_max_slippage_bps=9000 # default value
entry_max_auto_slippage_bps=0 # default value - setting this > 0 will bypass min/max slippage bps and use auto calculated by Jupiter, up to your max
entry_max_accounts=0 # default value - exclude this or keep at 0 to not use this setting
entry_dexes=[] # default empty - exclude this or keep empty to not use this setting
entry_exclude_dexes=[] # default empty - exclude this or keep empty to not use this setting
entry_max_price_impact=0 # default value - setting this > 0 will prevent swaps that the entry reports back a price impact percent > entry_max_price_impact

# Exit quote settings - Refer to entry quote settings comments
exit_only_direct_routes=false
exit_restrict_intermediate_tokens=false
exit_min_slippage_bps=2500
exit_max_slippage_bps=9000
exit_max_auto_slippage_bps=0
exit_max_accounts=0
exit_dexes=[]
exit_exclude_dexes=[]
exit_max_price_impact=0

# Jito transaction settings - Exclude all jito tip settings or set all to 0 to not use Jito transactions
jito_tip_percent=0 # default value
min_pref_jito_tip=0 # default value - "pref" means preferred, meaning it will try to keep your tip at least this amount if it means your tx still profits
max_pref_jito_tip=0 # default value - "pref" isn't really necessary here - this is the max jito tip your tx can have

# Normal transaction settings - If you don't want normal txs sending, do not include any settings for them
[[strategy_example_doc.normal_tx]]
rpc_key="example_rpc_key"
min_profit_lamports=1234 # the minimum ESTIMATED profit lamports for this to send
cooldown_ms=30_000 # the amount of ms to wait before trying to send with this configuration again (0 is no limit)


####################################
#        Define your swaps!        #
####################################

# USDC
[[swap]]
mint="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
decimals=6

[swap.strategy_defaults]
priority_fee_profit_factor=0.25
min_priority_fee_lamports=190
max_priority_fee_lamports=1900
jito_tip_percent=10
min_pref_jito_tip=1000
max_pref_jito_tip=10000

[[swap.strategy]]
# Small
min_spend=0.25
max_spend=1
max_pref_jito_tip=2500

[[swap.strategy]]
# Med
min_spend=1
max_spend=2.50
max_pref_jito_tip=5000

[[swap.strategy]]
# Large
min_spend=2.50
max_spend=5
max_pref_jito_tip=7500

[[swap.strategy]]
# X-Large
min_spend=5
max_spend=10
max_pref_jito_tip=10000

[[swap.strategy]]
# XX-Large
min_spend=10
max_spend=25
min_pref_jito_tip=2500
max_pref_jito_tip=12500

[[swap.strategy]]
# XXX-Large
min_spend=25
max_spend=50
min_pref_jito_tip=5000
max_pref_jito_tip=15000

# SOL
[[swap]]
mint="So11111111111111111111111111111111111111112"
decimals=9

[swap.strategy_defaults]
wrap_unwrap_sol=false
priority_fee_profit_factor=0.25
min_priority_fee_lamports=190
max_priority_fee_lamports=1900
jito_tip_percent=10
min_pref_jito_tip=1000
max_pref_jito_tip=10000

[[swap.strategy]]
# Small
min_spend=0.0001
max_spend=0.001
max_pref_jito_tip=2500

[[swap.strategy]]
# Med
min_spend=0.001
max_spend=0.01
max_pref_jito_tip=5000

[[swap.strategy]]
# Large
min_spend=0.01
max_spend=0.1
max_pref_jito_tip=7500

[[swap.strategy]]
# X-Large
min_spend=0.1
max_spend=0.5
max_pref_jito_tip=10000