@echo off

rem Define lib path
set "lib_path=%~dp0"

rem Remove trailing slash from lib path if it exists
if "%lib_path:~-1%"=="\" (
    set "lib_path=%lib_path:~0,-1%"
)

rem Set BOT_PATH to default path if not defined
if not defined BOT_PATH (
    rem This default path is auto generated by our release task
    set "BOT_PATH=%lib_path%\..\..\NotArbBot-0.0.1-alpha"
)

rem Ensure BOT_PATH file exists
if not exist "%BOT_PATH%" (
    echo Error: BOT_PATH file does not exist
    echo %BOT_PATH%
    pause & exit
)

rem Ensure CONFIG_PATH is defined
if not defined CONFIG_PATH (
    echo Error: CONFIG_PATH not defined
    pause & exit
)

rem Ensure CONFIG_PATH file exists
if not exist %CONFIG_PATH% (
    echo Error: CONFIG_PATH file does not exist
    echo %CONFIG_PATH%
    pause & exit
)

rem Java exe check
if not defined JAVA_EXE_PATH (
    rem Attempt to install Java if necessary
    call "%lib_path%\install_java.bat"
) else (
    echo %JAVA_EXE_PATH%
    "%JAVA_EXE_PATH%" --version
    if %errorlevel% neq 0 (
        echo Warning: Java could not be verified.
    )
)

rem Java vm_args check
if "%~1"=="" (
    echo Warning: No vm_args set, this is not advised.
) else (
    echo vm_args=%*
)

rem Misc debug
echo BOT_PATH=%BOT_PATH%
echo CONFIG_PATH=%CONFIG_PATH%

rem Run bot
"%JAVA_EXE_PATH%" %* -Dcaller_script_dir="%CD%" -cp "%BOT_PATH%" org.notarb.launcher.Main "%CONFIG_PATH%"
echo Bot exited with code %ERRORLEVEL%
pause