# For more in-depth information on configuration, please visit:
# https://config.notarb.org/

[bot_misc]
keypair_path="/path/to/keypair.json OR /path/to/keypair.txt" # required for signing transactions
swap_threads=0 # Leave at 0 if not sure.
jito_threads=0 # Leave at 0 if not sure.
spam_threads=0 # Not needed for Jito.

[jupiter]
url="http://127.0.0.1:8080/"
http_timeout_ms=3000
http_pool_max_size=50

####################################################################################################

[[jito]]
enabled=true
url="https://ny.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
http_pool_max_size=5
requests_per_second=5
queue_timeout_ms=7500

[[jito]]
enabled=true
url="https://slc.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
http_pool_max_size=5
requests_per_second=5
queue_timeout_ms=7500

[[jito]]
enabled=true
url="https://frankfurt.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
http_pool_max_size=5
requests_per_second=5
queue_timeout_ms=10_000

[[jito]]
enabled=true
url="https://amsterdam.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
http_pool_max_size=5
requests_per_second=5
queue_timeout_ms=12_500

[[jito]]
enabled=true
url="https://tokyo.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
http_pool_max_size=5
requests_per_second=5
queue_timeout_ms=15_000

####################################################################################################

[dynamic_mints]
enabled=true
limit=100

exclude=[ # optional
    "So11111111111111111111111111111111111111112",  # sol
    "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB", # usdt
    "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", # usdc
]

## NOTE: Filter configurations must be placed at the end, after other settings like exclude and enabled. ##

[[dynamic_mints.filter]]
include_tags=[
    ["birdeye-trending"]
]

[[dynamic_mints.filter]]
min_daily_volume=50_000

####################################
#        Define your swaps!        #
####################################

#########
#  SOL  #
#########
[[swap]]
enabled=true
mint="SOL"

[swap.strategy_defaults]
wrap_unwrap_sol=false
jito_enabled=true

[[swap.strategy]]
min_spend=0.0001
max_spend=0.01
jito_static_tip_lamports=5000

[[swap.strategy]]
min_spend=0.5
max_spend=1
jito_dynamic_tip_percent=40

##########
#  USDC  #
##########
[[swap]]
enabled=false
mint="USDC"

[swap.strategy_defaults]
wrap_unwrap_sol=false
jito_enabled=true

[[swap.strategy]]
min_spend=5
max_spend=50
jito_static_tip_lamports=5000

[[swap.strategy]]
min_spend=10
max_spend=100
jito_dynamic_tip_percent=40