# THIS CONFIG IS OUTDATED
# THIS CONFIG IS OUTDATED
# THIS CONFIG IS OUTDATED

# Define your desired rpc configurations, identified by "key" which must be unique.
# Use the key in other configurations that require rpc servers.

[[rpc]] # this is just an example rpc configuration, we recommend changing it (be sure to also change the blockhash_fetcher rpc_keys below)
key="solana-public"
url="https://api.mainnet-beta.solana.com"
http_timeout_ms=5000
requests_per_second=10
thread_pool_size=1

[[jito]]
url="https://ny.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
requests_per_second=5
thread_pool_size=1
queue_timeout_ms=5000

[[jito]]
url="https://frankfurt.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
requests_per_second=5
thread_pool_size=1
queue_timeout_ms=7000

[[jito]]
url="https://amsterdam.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
requests_per_second=5
thread_pool_size=1
queue_timeout_ms=9000

[[jito]]
url="https://tokyo.mainnet.block-engine.jito.wtf"
http_timeout_ms=3000
requests_per_second=5
thread_pool_size=1
queue_timeout_ms=11000

[jupiter]
url="http://0.0.0.0:8080/"
http_timeout_ms=3000
requests_per_second=0 # not used when unmetered=true
thread_pool_size=0 # not used when unmetered=true
unmetered=true

# Miscellaneous bot configuration

[bot_misc]
keypair_path="/path/to/keypair.json OR /path/to/keypair.txt" # required for signing transactions

[swap_executor]
max_threads=10 # these are lightweight "virtual" threads: https://openjdk.org/jeps/444 (although you can use more of them compared to normal threads, they will still eat up cpu so scale wisely)
max_queue_size=100 # how many swap tasks can be queued at once

[blockhash_fetcher]
rpc_keys=["solana-public"]
fetch_rate_ms=200 # the rate at which latest blockhash fetch tasks should execute
task_timeout_ms=3000 # how long should a fetch task wait before cancelling

[raydium_token_scanner]
enabled=false
wss_url="must be set to use" # used to subscribe to token programs for quoting
min_token_pool_age="24h" # accepted format examples: "15m", "5h", "1d"
amm_pools=true # if true, scan standard liquidity pools for tokens
clmm_pools=true # if true, scan concentrated liquidity pools for tokens
max_queue_size=500 # stop adding new tokens to the swap queue at this size
max_price_impact=0.01 # value as a percent (ex: 0.05 = 5%) - helps filter out low liquidity tokens
untradeable_token_timeout="15m" # if a token quote returns an untradeable response from jupiter, define how long you'd like for that specific token to be able to try again
exclude_mints=[ # enabled token_list mints will be added to this list by default
    "So11111111111111111111111111111111111111112",  # sol
    "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", # usdc
    "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB", # usdt
]

[[token_list]]
enabled=true
random_order=true
mints=[
    "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB", # usdt
    "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", # usdc
    "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R", # ray
    "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn", # jitosol
    "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",  # msol
    "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj", # stsol
    "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs", # weth
    "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh", # wbtc
    "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",  # jup
    "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3", # pyth
    "HNTvzaqTmDxJbi3isreXtUn9MUJEJy1bp9bo1rpGEGhi", # aurasol
    "jucy5XJ76pHVvtPZb5TKRcGQExkwit2P5s4vY8UzmpC",  # jucysol
]

####################################
#        Define your swaps!        #
####################################

# SOL
[[swap]]
enabled=true
mint="So11111111111111111111111111111111111111112"
decimals=9

[swap.strategy_defaults]
wrap_unwrap_sol=false
min_priority_fee_lamports=190
max_priority_fee_lamports=190
jito_tip_percent=10
min_pref_jito_tip=1000
max_pref_jito_tip=10000
entry_max_slippage_bps=10000
exit_max_slippage_bps=10000

[[swap.strategy]]
# Small
min_spend=0.0001
max_spend=0.001
max_pref_jito_tip=2500

[[swap.strategy]]
# Med
min_spend=0.001
max_spend=0.01
max_pref_jito_tip=5000

[[swap.strategy]]
# Large
min_spend=0.01
max_spend=0.1
max_pref_jito_tip=7500

[[swap.strategy]]
# X-Large
min_spend=0.1
max_spend=0.5
min_pref_jito_tip=5000
max_pref_jito_tip=10000

# USDC
[[swap]]
enabled=false
mint="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
decimals=6

[swap.strategy_defaults]
wrap_unwrap_sol=false
min_priority_fee_lamports=190
max_priority_fee_lamports=190
jito_tip_percent=10
min_pref_jito_tip=1000
entry_max_slippage_bps=10000
exit_max_slippage_bps=10000

[[swap.strategy]]
# Small
min_spend=0.25
max_spend=1
max_pref_jito_tip=2500

[[swap.strategy]]
# Med
min_spend=1
max_spend=2.50
max_pref_jito_tip=5000

[[swap.strategy]]
# Large
min_spend=2.50
max_spend=5
max_pref_jito_tip=7500

[[swap.strategy]]
# X-Large
min_spend=5
max_spend=10
max_pref_jito_tip=10000

[[swap.strategy]]
# XX-Large
min_spend=10
max_spend=25
min_pref_jito_tip=2500
max_pref_jito_tip=12500

[[swap.strategy]]
# XXX-Large
min_spend=25
max_spend=40#50
min_pref_jito_tip=5000
max_pref_jito_tip=15000