# This is an extremely basic SOL strategy, please refer to
# https://github.com/NotArb/JupiterBot/tree/main/examples
# for more complex strategy examples!

# TODO

# For now, use examples/jito-sol.toml
# https://github.com/NotArb/JupiterBot/tree/main/examples/jito-spam.toml